## Characters - Player
define player = Character(_("[var_string_playername]"), color="#636363")
define narrator = Character(_(""), color="#636363", what_italic=True)
define event = Character(_(""), color="#636363", what_italic=True)

## Characters - Students
define locke = Character(_("Locke"), color="#7541b8")
define locke_hall_monitor = Character(_("Hall Monitor"), color="#7541b8")
define cameron = Character(_("Cameron"), color="#00718f")
define chris = Character(_("Chris"), color="#b32228")
define jimmy = Character(_("Jimmy"), color="#796100")
define jake = Character(_("Jake"), color="#00737f")
define johnny = Character(_("Johnny"), color="#b22800")
define july = Character(_("July"), color="#00766b")
define edward = Character(_("Edward"), color="#0063c3")
define faith = Character(_("Faith"), color="#307600")
define randy = Character(_("Randy"), color="#954f00")
define laine = Character(_("Laine"), color="#ad215f")
define jesse = Character(_("Jesse"), color="#905300")
define luthor = Character(_("Luthor"), color="#7e5e00")
define jessica = Character(_("Jessica"), color="#a4277a")
define keith = Character(_("Keith"), color="#0c7900")
define avery = Character(_("Avery"), color="#881fc4")
define sienna = Character(_("Sienna"), color="#ac3600")
define marie = Character(_("Marie"), color="#0092ac")

## Characters - Teachers
define teacher_jackson = Character(_("Mr. Jackson"), color="#3e55c8")
define teacher_moore = Character(_("Mr. Moore"), color="#307700")
define teacher_warmuth = Character(_("Ms. Warmuth"), color="#9c5679")
define teacher_abulmi = Character(_("Mr. Abulmi"), color="#6f6600")
define teacher_obrien = Character(_("Mr. O'Brien"), color="#507000")
define teacher_ingram = Character(_("Ms. Ingram"), color="#575757")
define teacher_reyes = Character(_("Dr. Reyes"), color="#70004b")
define teacher_galloni = Character(_("Mr. Galloni"), color="#706800")
define teacher_legliter = Character(_("Mrs. Legliter"), color="#705200")
define teacher_moon = Character(_("Mr. Moon"), color="#2a077c")